#!/usr/bin/bash

ext=`date +%w`
ext='0'

# -----------------------------------------------------------
# Empty trash
# -----------------------------------------------------------

/home/dvdaf/scripts/empty-trash.php

# -----------------------------------------------------------
# Delete old uploads
# -----------------------------------------------------------

#find /var/www/html/uploads/* -maxdepth 1 -type f -mtime +20 -exec rm -f {} \;

# -----------------------------------------------------------
# Ajax lookups
# -----------------------------------------------------------

cd /home/dvdaf/scripts
/home/dvdaf/scripts/min-dir-stu.php
/home/dvdaf/scripts/min-title.php

# -----------------------------------------------------------

